package terminal;

public enum Terminal {
    INCREMENT, DECREMENT,
    MULTIPLY, DIVIDE,
    ADD, SUBSTRACT,
    EQUALS, NOT_EQ,
    LESSER, LESSER_EQ, GREATER, GREATER_EQ,
    OR, AND,
    ASSIGN,
    LEFT_PARA, RIGHT_PARA,
    LEFT_CURLY, RIGHT_CURLY,
    LEFT_SQ, RIGHT_SQ,
    COMMA, EOF, SEMICOLON,
    INT, FLOAT,
    IF, ELSE,
    FOR,
    INPUT, PRINT,
    RETURN,
    INT_VAL, FLOAT_VAL, IDENTIFIER
}
