package nonterminal;

public enum NonTerminal {
    PROGRAM,
    FUNCTIONS, FUNCTION,
    PARAMETERS, PARAMETER, OTHER_PARAMS,
    TYPE, TYPE_PART_1, TYPE_PART_2,
    BLOCK,
    STATEMENTS, STATEMENT, COMPOUND_STMT,
    DECLARATION, IDENTIFIERS, OTHER_IDS,
    ASSIGNMENT, VARIABLE, VARIABLE_OPT, VALUE,
    ARRAY, ARRAY_ELEMS, OTHER_ELEMS,
    INC_DEC_STMT,
    IO_STMT,
    IF_STMT, ELSE_STMT,
    FOR_STMT,
    RETURN_STMT,
    FUNCTION_STMT, FUNC_EXPR,
    ARGUMENTS, ARGUMENT, OTHER_ARGS,
    MUL_OP,
    ADD_OP,
    REL_OP,
    OR_OP, AND_OP,
    NUM_EXPR, N_, T, T_, F,
    BOOL_EXPR, B_, X, X_, Y
}
